
(defrule goal-expander-create-sequence
	?g <- (goal (mode SELECTED) (id TESTGOAL))
	=>
	(assert
		(plan (id TESTGOAL-PLAN) (goal-id TESTGOAL))
		(plan-action (id 1) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp_init" "wp1"))
		(plan-action (id 2) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp1" "wp_init"))
		(plan-action (id 3) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp_init" "wp2"))
		(plan-action (id 4) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp2" "wp_init"))
		(plan-action (id 5) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp_init" "wp3"))
		(plan-action (id 6) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp3" "wp_init"))
		(plan-action (id 7) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp_init" "wp4"))
		(plan-action (id 8) (plan-id TESTGOAL-PLAN) (duration 4.0)
		             (action-name move) (goal-id TESTGOAL)
		             (param-names r1 w1 w2) (param-values "robotino1" "wp4" "wp_init"))
	)
	(modify ?g (mode EXPANDED))
)
