
clips_features_manager:
  ros__parameters:
    clips_features: ["clips_pddl_parser", "skill_execution", "clips_protobuf"]

    mock_feature:
      plugin: "cx::MockFeature"
    plansys2:
      plugin: "cx::Plansys2Feature"
    clips_pddl_parser:
      plugin: "cx::ClipsPddlParserFeature"
    skill_execution:
      plugin: "cx::SkillExecutionFeature"
    clips_protobuf:
      plugin: "cx::ClipsProtobufFeature"
      feature_parameters: ["protobuf-path"]
      protobuf-path:
        # This path assumes relativeness to the workspace
        value: "src/ros2-clips-executive/cx_bringup/proto"
        type: "string"


cx_clips:
  ros__parameters:
    alpha1: 0.2
